"""
SpacerNet: A tool for building CRISPR array spacer-sharing networks from multi-strain GFF files.
Will Heisler
04/15/2025

This script performs the following steps:
1. Extracts spacer sequences from a combined multi-strain GFF file generated by CRISPRCasFinder, 
filtering for arrays with a minimum number of spacers.
2. Writes the extracted spacers to a FASTA file with unique headers that include the strain name and spacer ID.
3. Runs BLASTn on the spacer FASTA file against itself to identify shared 
spacers between strains, applying a percent identity threshold.
4. Builds a spacer-sharing network using NetworkX, where nodes represent 
strains and edges represent shared spacers, colored by the number of spacers shared between them.
5. Saves the edge table and network figure to specified output files.

Usage:
    python spacerNet.py <input_gff_file> <output_prefix>
Example:
    python spacerNet.py combined_strains.gff spacer_network
Notes:
- The script requires BLAST+ installed in the system PATH, pandas, NetworkX, and matplotlib to be installed.
- The input GFF file should be a combined multi-strain file with 
strain headers of the format "speciesTag_strainID_int" and CRISPR array features annotated by CRISPRCasFinder.

"""
import sys
import re

def gff_to_fasta(input_file, spacer_output_file, min_spacers=1):
    """
    Extracts spacer sequences from a combined multi-strain GFF file and writes them to a FASTA file.
    For each strain, only spacers belonging to arrays with more than `min_spacers` spacers are included.
    The FASTA headers include the strain name as a prefix (e.g., >bh11_sp_2039887).
    
    Parameters
    ----------
    input_file : str
        Path to the combined multi-strain GFF file.
    
    spacer_output_file : str
        Path to the output FASTA file for spacers.
    
    min_spacers : int, optional
        Minimum number of spacers required for an array to be considered valid (default is 1).
    """

    valid_arrays = set()
    strain_name = "unknown_strain"
    strain_arrays = {}  # maps strain - set of valid arrays

    # ---------- PASS 1: Identify valid arrays per strain ----------
    print('-'*50)
    print("Identifying valid CRISPR arrays per strain...")
    with open(input_file, 'r') as f:
        for line in f:
            # Detect new strain header line
            strain_match = re.search(r"strain[:=]\s*([A-Za-z0-9_-]+)", line)
            if strain_match:
                strain_name = strain_match.group(1)
                if strain_name not in strain_arrays:
                    strain_arrays[strain_name] = set()
                continue

            if line.startswith("#"):
                continue

            fields = line.strip().split("\t")
            if len(fields) < 9:
                continue

            feature_type = fields[2]
            attributes = fields[8]

            # Identify valid CRISPR arrays
            if feature_type == "CRISPR":
                num_match = re.search(r"Number_of_spacers=(\d+)", attributes) 
                name_match = re.search(r"Name=([^;]+)", attributes)
                if num_match and name_match:
                    num_spacers = int(num_match.group(1))
                    array_name = name_match.group(1)
                    if num_spacers >= min_spacers : # SPACER FILTERING CONDITION
                        strain_arrays[strain_name].add(array_name)

    # ---------- PASS 2: Write spacers for valid arrays ----------
    current_strain = "unknown_strain"
    print(f"Writing spacers to FASTA for arrays with >= {min_spacers} spacers...")
    with open(input_file, 'r') as f, open(spacer_output_file, 'w') as out:
        for line in f:
            # Update strain whenever a new header is encountered
            strain_match = re.search(r"strain[:=]\s*([A-Za-z0-9_-]+)", line)
            if strain_match:
                current_strain = strain_match.group(1)
                continue

            if line.startswith("#"):
                continue

            fields = line.strip().split("\t")
            if len(fields) < 9 or fields[2] != "CRISPRspacer":
                continue

            attributes = fields[8]
            seq_match = re.search(r"sequence=([^;]+)", attributes)
            id_match = re.search(r"ID=([^;]+)", attributes)
            parent_match = re.search(r"Parent=([^;]+)", attributes)

            if seq_match and id_match and parent_match:
                sequence = seq_match.group(1)
                spacer_id = id_match.group(1)
                parent_id = parent_match.group(1)

                # Check if spacer belongs to a valid array for the current strain
                if current_strain in strain_arrays and parent_id in strain_arrays[current_strain]:
                    out.write(f">{current_strain}_{spacer_id}\n{sequence}\n")
    
    print(f"Finished writing spacers to {spacer_output_file}. Total strains: {len(strain_arrays)}")

def run_blast(spacer_fasta, blast_perc_id, out_prefix):
    """
    Runs BLASTn on the spacer FASTA file against itself and returns a DataFrame of results.
    Only hits meeting the specified percent identity threshold are included.

    Parameters
    ----------

    spacer_fasta : str
        Path to the spacer FASTA file.

    perc_id : float
        Percent identity threshold for BLAST hits.

    out_prefix : str
        General file name prefix for BLAST output files (database and results).
    """
    
    import subprocess
    import pandas as pd

    db = f"{out_prefix}_db"
    out = f"{out_prefix}_blast.tsv"

    # ---------- Build database -----------
    print('-'*50)
    print("Building BLAST database...")
    subprocess.run([
        "makeblastdb",
        "-in", spacer_fasta,
        "-dbtype", "nucl",
        "-out", db
    ], check=True)

    # ---------- Run BLAST ----------
    print("Running BLAST...")
    subprocess.run([
        "blastn",
        "-query", spacer_fasta,
        "-db", db,
        "-outfmt", "6 qseqid sseqid pident length qlen slen mismatch gapopen bitscore evalue",
        "-perc_identity", str(blast_perc_id),
        "-out", out
    ], check=True)

    df = pd.read_csv(out, sep="\t", header=None)
    df.columns = ["qseqid","sseqid","pident","length","qlen","slen", "mismatch","gapopen","bitscore","evalue"]

    # ---------- Remove self-hits and deduplicate symmetric hits ----------
    df = df[df["qseqid"] != df["sseqid"]]
    df["pair"] = df.apply(
        lambda x: tuple(sorted([x["qseqid"], x["sseqid"]])), axis=1
    )
    df = df.drop_duplicates("pair")

    print(f"BLAST completed. Total hits: {len(df)}")
    return df

def build_network(
    blast_df,
    net_perc_identity=95,
    min_length=20,
    remove_singletons=False,
    save_edges=None,
    output_figure=None,
    strain_parser=None,
    color_map=None,
    node_color_mode= 'species', # 'species' or 'strain'
    title="Spacer Sharing Network",
    figsize=(10, 9),
    layout_k=2.0,
    seed=10
):
    """
    Build and optionally plot the spacer-sharing network from BLAST results using NetworkX.

    Parameters
    ----------
    blast_df : pandas.DataFrame
        Must contain at least: qseqid, sseqid, pident, length

    perc_identity : float
        Minimum percent identity threshold

    min_length : int
        Minimum alignment length

    remove_singletons : bool
        If True, removes edges with weight = 1 and resulting isolated nodes

    save_edges : str or None
        Path to save edge table CSV

    output_figure : str or None
        Path to save network figure

    strain_parser : function or None
        Function to extract strain ID from sequence ID

    color_map : dict or None
        Mapping of strain prefix → color

    node_color_mode : str
        'species' to color by species prefix, 'strain' to color by full strain ID

    Returns
    -------
    G : networkx.Graph
    edges : pandas.DataFrame
    """

    import pandas as pd
    import networkx as nx
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import matplotlib
    import seaborn as sns

    # ---------- Defaults ----------
    if strain_parser is None:
        strain_parser = lambda x: "_".join(x.split("_")[:2]) # default: speciesTag_ID_int

    # ---------- Filter BLAST ----------
    print('-'*50)
    print("Building spacer sharing network...")
    print(f"Filtering BLAST results with {net_perc_identity}% identity and {min_length} bp length thresholds...")
    df = blast_df.copy()

    df = df[
    (df["length"] >= min_length) & (df["pident"] >= net_perc_identity)
    ]
    print(f"Number of hits after filtering: {len(df)}")

    # ---------- Extract strains ----------
    df["strain1"] = df["qseqid"].apply(strain_parser)
    df["strain2"] = df["sseqid"].apply(strain_parser)

    # ---------- Build edge table ----------
    edges = df.groupby(["strain1", "strain2"]).size().reset_index(name="weight")

    # Save edges if requested
    if save_edges:
        edges.to_csv(save_edges, index=False)

    # ---------- Optional filtering ----------
    if remove_singletons:
        edges = edges[edges["weight"] > 1]

    # ---------- Determine nodes ----------
    if remove_singletons:
        strains = set(edges["strain1"]) | set(edges["strain2"])
    else:
        strains = set(blast_df["qseqid"].apply(strain_parser)) | \
                  set(blast_df["sseqid"].apply(strain_parser))

    # ---------- Build graph ----------
    print(f"Building graph with {len(strains)} strains...")
    G = nx.Graph()
    G.add_nodes_from(strains)

    for _, row in edges.iterrows():
        G.add_edge(row["strain1"], row["strain2"], weight=row["weight"])

    # ---------- Plotting ----------
    if output_figure:
        edge_weights = [d["weight"] for (_, _, d) in G.edges(data=True)]

        if len(edge_weights) == 0:
            print("Warning: No edges to plot.")
            return G, edges

        norm = matplotlib.colors.Normalize(
            vmin=min(edge_weights),
            vmax=max(edge_weights)
        )
        cmap = plt.cm.plasma ## Edge color map
        edge_colors = [cmap(norm(w)) for w in edge_weights]

        # ---------- Node colors ----------
        # Determine grouping key (prefix or full strain)
        def get_species(node):
            # speciesTag from speciesTag_ID_int
            return node.split("_")[0]

        def get_strain(node):
            # full strain ID: speciesTag_ID_int
            parts = node.split("_")
            return "_".join(parts) if len(parts) >= 2 else parts[0]

        # Select grouping behavior
        if node_color_mode == "species":
            grouping_func = get_species
        elif node_color_mode == "strain":
            grouping_func = get_strain
        else:
            raise ValueError("node_color_mode must be 'species' or 'strain'")

        # Determine unique groups
        groups = sorted(set(grouping_func(n) for n in G.nodes()))

        # Choose colors for groups
        if color_map is None:
            colors = sns.color_palette("deep", n_colors=len(groups))
            group_to_color = dict(zip(groups, colors))
        else:
            group_to_color = color_map  # user-provided dict

        # Assign node colors based on group
        node_colors = [
            group_to_color.get(grouping_func(node), "gray")
            for node in G.nodes()
        ]

        # ---------- Layout and plot ----------
        pos = nx.spring_layout(G, k=layout_k, seed=seed)

        plt.figure(figsize=figsize)

        nx.draw_networkx_nodes(
            G, pos,
            node_color=node_colors,
            node_size=600,
            alpha=0.9
        )

        nx.draw_networkx_edges(
            G, pos,
            width=1.8,
            edge_color=edge_colors
        )

        nx.draw_networkx_labels(
            G, pos,
            font_size=5.5,
            font_family="Calibri",
            font_weight="regular",
            font_color="black"
        )

        # Legend (auto-generated from color_map)
        legend_handles = [
            mpatches.Patch(color=color, label=group)
            for group, color in group_to_color.items()
        ]
        plt.legend(handles=legend_handles, loc="upper right",
                   frameon=False, fontsize=8)

        # Colorbar
        sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
        cbar = plt.colorbar(sm, ax=plt.gca(), shrink=0.7)
        cbar.set_label("Number of Shared Spacers", fontsize=10, labelpad=10)

        plt.title(title)
        plt.tight_layout()
        plt.savefig(output_figure, dpi=600,
                    bbox_inches='tight', transparent=True) # Add function for save as eps
        plt.show()
        print('Finished building network.')
        print('-'*50)

    return G, edges

if __name__ == "__main__":
    if len(sys.argv) < 3 or len(sys.argv) > 4:
        print("Usage: python spacerNet.py <input_file> <output_file>")
        sys.exit(1)

    # ---------- Parameters ----------
    input_file = sys.argv[1]
    general_output = sys.argv[2]
    min_spacers = input("Enter minimum number of spacers needed for a valid array (default 1): ")
    min_spacers = int(min_spacers) if min_spacers else 1

    # ---------- Extract spacers to FASTA ----------
    fasta_output_file = general_output + "_spacers.fasta"
    gff_to_fasta(input_file, fasta_output_file, min_spacers)
    print(f"Spacer FASTA file created: {fasta_output_file}.")
    print('-'*50)

    # ---------- Run BLAST ----------
    blast_perc_id = input("Enter BLAST percent identity threshold (default 95): ")
    blast_perc_id = float(blast_perc_id) if blast_perc_id else 95
    blast_df = run_blast(fasta_output_file, blast_perc_id, general_output)
    blast_df.to_csv(f"{general_output}_blast.csv", index=False)
    print(f"BLAST completed and results saved to {general_output}_blast.csv")
    print('-'*50)

    # ---------- Build network ----------
    net_perc_id = input("Enter percent identity threshold for network (default 95): ")
    net_perc_id = float(net_perc_id) if net_perc_id else 95
    node_color_mode = input("Color nodes by 'species' or 'strain'? (default 'species'): ")
    node_color_mode = node_color_mode if node_color_mode in ['species', 'strain'] else 'species'
    G, edges = build_network(
        blast_df,
        net_perc_identity=net_perc_id,
        min_length=20,
        remove_singletons=True,
        save_edges=f"{general_output}_edges.csv",
        output_figure=f"{general_output}_network.png", 
        node_color_mode=node_color_mode, 
        color_map=None
    )
    print(f"Network built and figure saved to {general_output}_network.png")
    print(f"Edges saved to {general_output}_edges.csv")
    print('**DONE**')
    print('-'*50)



